# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Zyteaの小站
author: ZTE
email: 124090991@link.cuhk.edu.cn
description: >- # this means to ignore newlines until "baseurl:"
  Zyteaの小站，记录生活点滴与学习笔记。
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://Zytea.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Zytea 
twitter_username: zyteauth

# Jekyll
logo: "/assets/images/Astesia.png" # 你自己的logo（需要文件）
favicon: "/assets/images/favicon.ico" # 站点图标（需要文件）

paginate: 5 # 分页，每页显示几篇文章

timezone: Asia/Shanghai # 时区

permalink: /:year/:month/:day/:title/ # 文章链接样式

google_analytics: G-F9MHHXE0XZ   # Google分析ID
show_excerpts: true                # 显示文章摘要
excerpt_separator: "<!--more-->"

# 定制导航栏（header）
header_pages:
  - categories.md
  - about.md

favicon: "/docs/assets/images/favicon.ico"
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
